contact_links:
  - name: I have a question ðŸ¤”
    url: https://github.com/WSH032/fastapi-proxy-lib/discussions
    about: If you have any question that's not clearly a bug, please open a discussion first.
